version: '3.9'

services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - /data/db:/data/mongodb/db
    ports:
      - 27017:27017
  web:
    build: .
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
